# Generated by Django 5.2.15 on 2026-06-16 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn13', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('pub_year', models.IntegerField(blank=True, null=True)),
                ('kdc_code', models.CharField(blank=True, max_length=20)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_book', models.BooleanField(default=False)),
                ('loan_available', models.BooleanField(default=False)),
                ('snapshot_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='books.book')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='books.library')),
            ],
            options={
                'unique_together': {('library', 'book')},
            },
        ),
    ]
