# Generated by Django 5.2.15 on 2026-06-16 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_signals', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='CoLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coloans_as_base', to='books.book')),
                ('co_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coloans_as_target', to='books.book')),
            ],
            options={
                'unique_together': {('book', 'co_book')},
            },
        ),
    ]
