# Generated by Django 5.2.15 on 2026-06-24 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_loansignal_coloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEmbedding',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='books.book')),
                ('model', models.CharField(max_length=50)),
                ('vector', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
