# Generated by Django 5.2.15 on 2026-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='library',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
