# Generated by Django 5.2.15 on 2026-06-23 08:34

from django.db import migrations, models


def delete_wish_logs(apps, schema_editor):
    # 좋아요 통합(D28)으로 은퇴한 'wish' 상태의 잔여 ReadingLog 행 삭제
    ReadingLog = apps.get_model('accounts', 'ReadingLog')
    ReadingLog.objects.filter(status='wish').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bookpreference'),
    ]

    operations = [
        migrations.RunPython(delete_wish_logs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='readinglog',
            name='status',
            field=models.CharField(choices=[('reading', 'Reading'), ('finished', 'Finished')], max_length=10),
        ),
    ]
