# Generated by Django 5.2.15 on 2026-06-23 23:22

from django.db import migrations, models


def backfill_libraries(apps, schema_editor):
    # 기존 대표 도서관(primary_library)을 libraries M2M로 복사 (D29)
    Profile = apps.get_model('accounts', 'Profile')
    for profile in Profile.objects.exclude(primary_library__isnull=True):
        profile.libraries.add(profile.primary_library)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_readinglog_status'),
        ('books', '0002_loansignal_coloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='libraries',
            field=models.ManyToManyField(blank=True, related_name='member_profiles', to='books.library'),
        ),
        migrations.RunPython(backfill_libraries, migrations.RunPython.noop),
    ]
